# Generated by Django 6.0.3 on 2026-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eamil', models.CharField(max_length=50)),
                ('message', models.TextField(default=True)),
            ],
        ),
    ]
