# Generated by Django 6.0.3 on 2026-04-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageshow', models.TextField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='eamil',
            field=models.EmailField(max_length=50),
        ),
    ]
